services:
  backend:
    build:
      context: .
      dockerfile: WoodArtCons.Server/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - woodartcons-db:/root/WoodArtCons.md/WoodArtCons.Server/WoodArtCons.db
      - woodartcons-images:/root/WoodArtCons.md/WoodArtCons/wwwroot/Images
    restart: always

  frontend:
    build:
      context: .
      dockerfile: WoodArtCons/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - backend
    restart: always 

volumes:
  woodartcons-db:
  woodartcons-images: