name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: SSH into VPS
        uses: appleboy/ssh-action@master
        with:
          host: 195.178.106.159
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
