name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: WoodArtCons.sln                            # Replace with your solution name, i.e. MyWpfApp.sln.
      Server_Project_Path: WoodArtCons.Server                   # Path to the server project.
      Client_Project_Path: WoodArtCons                          # Path to the client project.
      Wap_Project_Directory: WoodArtCons.Package                # Directorul proiectului WAP relativ la soluție.
      Wap_Project_Path: WoodArtCons.Package/WoodArtCons.Package.wapproj  # Calea către fișierul .wapproj al proiectului WAP.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the solution to populate the obj folder with RuntimeIdentifiers
    - name: Restore the solution
      run: dotnet restore $env:Solution_Name

    # Build and test the Server project
    - name: Build and test Server project
      run: |
        dotnet build $env:Server_Project_Path -c ${{ matrix.configuration }}
        dotnet test $env:Server_Project_Path -c ${{ matrix.configuration }}

    # Build and test the Client project
    - name: Build and test Client project
      run: |
        dotnet build $env:Client_Project_Path -c ${{ matrix.configuration }}
        dotnet test $env:Client_Project_Path -c ${{ matrix.configuration }}

    # Create directory if it doesn't exist
    - name: Create WAP project directory
      run: New-Item -ItemType Directory -Force -Path $env:Wap_Project_Directory

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path $env:Wap_Project_Directory\GitHubActionsWorkflow.pfx

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
