name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: WoodArtCons.sln  
      Server_Project_Path: WoodArtCons.Server
      Client_Project_Path: WoodArtCons

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    # Build the solution
    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    # Run tests
    - name: Run tests
      run: dotnet test ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    # Publish artifacts (if needed)
    - name: Publish artifacts
      run: |
        dotnet publish ${{ env.Server_Project_Path }} --configuration ${{ matrix.configuration }} --output ./publish/Server
        dotnet publish ${{ env.Client_Project_Path }} --configuration ${{ matrix.configuration }} --output ./publish/Client

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PublishedApp
        path: ./publish
